apiVersion: v1
kind: Namespace
metadata:
  name: sentinel-ids
  labels:
    app.kubernetes.io/name: sentinel-ids
    app.kubernetes.io/part-of: sentinel-ids
    app.kubernetes.io/managed-by: kustomize
